# docker-compose.yml

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db/postgres
      SECRET_KEY: "your-very-secure-secret-key"  # Ensure this matches auth.py
    ports:
      - "8000:8000"
    volumes:
      - ./backend/app:/app/app

  frontend:
    build: ./frontend
    depends_on:
      - backend
    ports:
      - "3000:80"  # Nginx serves on port 80 inside the container
    volumes:
      - ./frontend:/app

volumes:
  db-data:
